# Generated by Django 5.2.3 on 2025-07-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_resume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='drive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
