# Generated by Django 5.2.3 on 2025-07-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_resume_file_resume_drive_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='drive_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='cv_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
