# Generated by Django 5.2.3 on 2025-07-08 05:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_resume_drive_url_remove_resume_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv'),
        ),
    ]
