# Generated by Django 5.2.3 on 2025-07-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_alter_resume_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
